version: "3.8"

services:
  db:
    image: postgres:15
    container_name: volunchain_db
    environment:
      POSTGRES_USER: volunchain
      POSTGRES_PASSWORD: volunchain123
      POSTGRES_DB: volunchain
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: volunchain_app
    environment:
      DATABASE_URL: postgres://volunchain:volunchain123@db:5432/volunchain
    command: sh -c "npx prisma migrate deploy && npm run start"
    depends_on:
      - db

volumes:
  db_data:
